# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_os_family in ["Debian","RedHat"]

- name: include OS family specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: ansible does exist
  package:
    name: ansible
    state: "{{ (ansible_install_latest == true)|ternary('latest','present') }}"

- name: ansible-lint does exist
  package:
    name: ansible-lint
    state: present

- name: ansible.cfg does exist
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
