---
sudo: required
dist: xenial
language: minimal
env:
  global:
    - ANSIBLE_ROLE_NAME=mafalb.ansible
    - CI=travis
    - ANSIBLE_FORCE_COLOR=1
  matrix:
    - targeted_ansible_version: 2.7
    - targeted_ansible_version: 2.8
      addons:
      apt:
        sources:
          - sourceline: "ppa:ansible/ansible-2.8"

before_install:
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH CI_BUILD_DIR=$TRAVIS_BUILD_DIR
  - env
  - dpkg -l
  - sudo -H pip install ansible-lint
  - pip list
  - docker --version
  - ansible localhost -m setup
  - ansible --version
install:
  - pwd
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/mafalb.ansible
script:
  - ansible-lint --force-color -v tests/test.yml
  - ansible-playbook --become -D tests/test.yml -C -t all,debug
  - ansible-playbook --become -D tests/test.yml    -t all,debug
