---
sudo: required
language: python
services:
  - docker
before_install:
  - apt-get install ansible
  - echo -e "localhost ansible_connection=local\n" >/etc/ansible/hosts
#install:
  #- pip install molecule
  #- pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
script:
  - ansible-playbook -D test/ansible.yml
