---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get install ansible
  - sudo echo -e "localhost ansible_connection=local\n" >/etc/ansible/hosts
#install:
  #- pip install molecule
  #- pip install required driver (e.g. docker, python-vagrant, shade, boto, apache-libcloud)
script:
  - ansible -i localhost, -c local test/ansible.yml
