# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
      - ansible_os_family in ["Debian","RedHat"]

- name: assertions
  when: ansible_os_family == 'Debian'
  assert:
    that:
      - ansible_distribution in ["Ubuntu"]

- name: dependencies for ansible does exist
  check_mode: "{{ ansible_check_mode|ternary(ansible_install_in_check_mode,false) }}"
  package:
    name: "{{ ansible.needed_packages }}"
    state: present

- name: pyOpenSSL is absent for RedHat
  when: 
    - ansible_distribution in ['CentOS', 'RedHat']
    - ansible_distribution_major_version == '7'
  package:
    name: pyOpenSSL
    state: absent

...
