# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_os_family in ["Debian","RedHat"]

- name: assertions
  when: ansible_os_family == 'Debian'
  assert:
    that:
      - ansible_distribution in ["Ubuntu"]

- name: dependencies for ansible does exist
  check_mode: "{{ ansible_check_mode|ternary(ansible_install_in_check_mode,true) }}"
  package:
    name: "{{ ansible.needed_packages }}"
    state: present
