# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_os_family in ["Debian","RedHat"]

- name: assertions
  when: ansible_os_family == 'Debian'
  assert:
    that:
      - ansible_distribution in ["Ubuntu"]

- name: set python major version fact
  set_fact:
    ansible_python_major_version: "{{ ansible_python_version|regex_replace('^([0-9]).*','\\1') }}"

- name: include OS specific data
  include_vars: "{{ ansible_os_family }}.yml"

- debug: var=ansible
  tags:
    - never
    - debug

- debug: var=ansible_python_major_version
  tags:
    - never
    - debug

- name: include OS family specific tasks for Debian
  when: ansible_os_family == "Debian"
  include: Debian.yml

- name: include OS family specific tasks for RedHat
  when: ansible_os_family == "RedHat"
  include: RedHat.yml

